### ISSUE TITLE
fix responsive padding

### ISSUE THREAD

**Issue by itsthatguy** [adorableio/ywebca-site#13]
In a medium-ish width the site does not have any padding between content and the edge of the browser.

<img width="814" alt="2015-07-06 at 2 29 pm" src="https://cloud.githubusercontent.com/assets/1118006/8529843/70c4569c-23eb-11e5-8482-0cbb27b3d3b1.png">

**Comment by itsthatguy** [comment]
<img width="947" alt="2015-07-06 at 2 30 pm" src="https://cloud.githubusercontent.com/assets/1118006/8529868/95e71176-23eb-11e5-9682-29c53bc47362.png">

**Comment by chriscoyier** [comment]
Fixed.

p.s. that `gulp deploy` action is pretty hot

**Comment by itsthatguy** [comment]
Awesome, thanks @chriscoyier ... and thanks!
