### ISSUE TITLE
Add partners section

### ISSUE THREAD

**Issue by whazzmaster** [adorableio/ywebca-site#5]
It would be nice to showcase the local companies that are partnering with the program (via site tours, internships, etc.) We should include them on the page similar to how to sponsors are listed for the conferences, however I would want to make sure we got permission from the companies before using any logos or names.

What say you, @bigtiger @m5rk?

**Comment by bigtiger** [comment]
Do eet, do eet now!

**Comment by chriscoyier** [comment]
New Site has a tech partners and funders section!
