### ISSUE TITLE
Add YWCA branding to site

### ISSUE THREAD

**Issue by whazzmaster** [adorableio/ywebca-site#7]
Heard from @bigtiger that the YWCA would like their brand featured on the page, which we didn't do on the first iteration as we didn't want to co-opt their branding without their explicit approval. It sounds like we should move forward with adding them to the page- just need to figure out the best means of doing that.

**Comment by chriscoyier** [comment]
On Site 2.0 I was asked by Kristy Lust to do this too, who sent over a logo and said the footer is fine, so I put it there.
