### ISSUE TITLE
haiku is cute, but ambiguous

### ISSUE THREAD

**Issue by ericanaughton** [adorableio/ywebca-site#8]
this is just an opinion, but i just noticed that the words "you don't have to stay" could be misinterpreted.  i was scrolling quickly through the site, and my eye caught this region with the haiku, mostly because the dark background stood out. so good job there! however, it took me a moment to realize what the phrase means and who it is aimed towards.  i first wondered if this message is regarding the volunteers, future students, or just viewers.  i also wondered if it meant "you don't have to stay committed all year long", or "you don't have to stay on this website". i peeked at the last line of the paragraph before the haiku and quickly realized that the message is intended for the volunteers, and that it means "you don't have to stay for the whole class period".  so that is my two-cents. i love the idea of a haiku. it does draw attention to itself nicely. so that's all for now.

**Comment by whazzmaster** [comment]
This is a good point- I think I was preemptively attempting to address issues that volunteers would have with committing to a 4 hour block. At this point it's likely best to remove the section entirely until we actually hear relevant feedback, at which point we could add it back in a better format.

Could you send a pull request to remove it?

**Comment by chriscoyier** [comment]
Gone in site 2.0
